// Exception handling in JavaScript 

try
{
       let a = [1,2,3,4,5,6,7,8];
        console.log(a);
        console.log(b);
}
catch(e)
{
    console.log("Error", e.message);
}